name: Deploy content to develop environment

on:
  push:
    branches: [ develop, feature/structure-checks ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Test content
      run: |
        ls -la
        cd checks
        pip install -U pytest
        pytest -rP

