name: Deploy content to develop environment

on:
  push:
    branches: [ develop, feature/structure-checks ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - uses: actions/checkout@v2
    - name: Test content
      env:
        CONTENT_DIR: ${{ HOME }}
      run: |
        cd checks
        pip3 install -U pytest
        pip3 install dataclasses
        python3 -m pytest -rP
    # - name: Set GCStorage CLI
    #   uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
    #   with:
    #     project_id: ${{ secrets.DEV_PROJECT_ID }}
    #     service_account_key: ${{ secrets.DEV_GA_CREDENTIALS }}
    # - name: Update revision
    #   run: |
    #     date +%s%3N > revision
    # - name: Deploy content to GCStorage
    #   env:
    #     CONTENT_BUCKET: dev-scala-zone-content
    #   run: |
    #     bash .github/workflows/deployToGcs.sh
    # - name: Update content
    #   env:
    #     AUTH_PASSWORD: ${{ secrets.DEV_KEYCLOAK_PASSWORD }}
    #     AUTH_URL:      ${{ secrets.DEV_KEYCLOAK_TOKEN_URL }}
    #     API_URL:       ${{ secrets.DEV_SZ_API_URL }}
    #   run: |
    #     bash .github/workflows/deployToScalazone.sh

