name: Deploy content to production environment

on:
  push:
    branches: [ master ]

jobs:
  build:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup GCStorage CLI
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GA_CREDENTIALS }}
    - name: Update revision
      run: |
        date +%s%3N > revision
    - name: Deploy content to GCStorage
      env:
        CONTENT_BUCKET: scala-zone-content
      run: |
        bash .github/workflows/deployToGcs.sh
    - name: Update content
      env:
        AUTH_PASSWORD: ${{ secrets.PROD_KEYCLOAK_PASSWORD }}
        AUTH_URL:      ${{ secrets.PROD_KEYCLOAK_TOKEN_URL }}
        API_URL:       ${{ secrets.PROD_SZ_API_URL }}
      run: |
        bash .github/workflows/deployToScalazone.sh