name: Deploy content to staging environment

on:
  push:
    branches: [ stage ]

jobs:
  build:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup GCStorage CLI
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: "scalazone-stage"
        service_account_key: ${{ secrets.STAGE_GA_CREDENTIALS }}
    - name: Update revision
      run: |
        date +%s%3N > revision
    - name: Deploy content to GCStorage
      env:
        CONTENT_BUCKET: stage-scala-zone-content
      run: |
        bash .github/workflows/deployToGcs.sh
    - name: Update content
      env:
        AUTH_PASSWORD: ${{ secrets.STAGE_KEYCLOAK_PASSWORD }}
        AUTH_URL:      ${{ secrets.STAGE_KEYCLOAK_TOKEN_URL }}
        API_URL:       ${{ secrets.STAGE_SZ_API_URL }}
      run: |
        bash .github/workflows/deployToScalazone.sh

  